version: 2

defaults: &defaults
  docker:
    - image: circleci/node:10.16.0
  working_directory: ~/repo

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: npm ci
      - run: npm run install
      - run: npm run test:lint
      - run: npm run test

  install_sam:
    docker:
      - image: circleci/python:2.7-jessie
    working_directory: ~/repo
    steps:
      - checkout
      - run: pip install --user aws-sam-cli

  deploy:
    <<: *defaults
    steps:
      - checkout
      - run: npm ci
      - run: npm run install
      - run: npm run package
      - run: npm run publish

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              ignore: master

  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - install_sam:
          requires:
            - build
      - deploy:
          requires:
            - install_sam
          filters:
            branches:
              only: master
