version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:10.16.0

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: npm run install
      - run: npm run test:lint
      - run: npm run test

  deploy:
    <<: *defaults
    steps:
      - run: npm run package
      - run: npm run publish

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              ignore: master

  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
