version: 2

jobs:
  build:
    docker:
      - image: circleci/node:10.16.0

    working_directory: ~/repo

    steps:
      - checkout
      - run: npm run install
      - run: npm run test:lint
      - run: npm run test

  deploy:
    docker:
      - image: circleci/node:10.16.0

    working_directory: ~/repo

    steps:
      - run: npm run package
      - run: npm run publish

workflows:
  version: 2

  build:
    jobs:
      - build:
          branches:
            ignore: master

  deploy:
    jobs:
      - build:
          branches:
            only: master
      - deploy:
          requires:
            - build
          branches:
            only: master
